version: '3.8'

services:
  app:
    build: .
    ports:
      - "7878:7878"
    volumes:
      - ./data:/data
    command: serve

  client:
    build: .
    volumes:
      - ./data:/data
    environment:
      - KEYSTONELIGHT_SERVER_ADDR=app:7878
    command: client

  test:
    build:
      context: .
      target: builder
    volumes:
      - .:/usr/src/keystonelight
      - cargo-cache:/usr/local/cargo/registry
    command: /bin/bash -c "while true; do sleep 1000; done"  # Keep container running
    environment:
      - RUST_BACKTRACE=1
      - RUST_TEST_THREADS=1

volumes:
  cargo-cache: {}