# Test stage
FROM rust:1.85-slim

# Install build and test dependencies
RUN apt-get update && apt-get install -y \
  pkg-config \
  libssl-dev \
  && rm -rf /var/lib/apt/lists/*

# Create a new empty shell project
WORKDIR /usr/src/keystonelight

# Copy the source code
COPY . .

# Run tests
CMD ["cargo", "test", "--all", "--verbose"]