version: '3.8'

services:
  keystonelight:
    build: .
    ports:
      - "7878:7878"
    volumes:
      - keystonelight_data:/var/lib/keystonelight
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "keystonelight-client", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/usr/src/keystonelight
      - cargo-cache:/usr/local/cargo/registry
    environment:
      - RUST_BACKTRACE=1
      - RUST_TEST_THREADS=8
      - CARGO_BUILD_JOBS=8
      - CARGO_TARGET_DIR=/usr/src/keystonelight/target
      - CARGO_HOME=/usr/local/cargo
    user: "${UID:-1000}:${GID:-1000}"

volumes:
  keystonelight_data:
  cargo-cache: